version: "3.8"
services:
    postgres:
        image: 'postgres:14.4'
        container_name: forms-gen-db-postgres
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test
        volumes:
            - ./db-data-prod/:/var/lib/postgresql/data/ # probably should be changed or removed
    

    rabbitmq:
        image: 'rabbitmq:3.10.7-management'
        container_name: forms-gen-rabbitmq
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq-data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./rabbitmq-data/mnesia-prod/:/var/lib/rabbitmq/mnesia/ # probably should be changed or removed


    forms-rest:
        build: 
            context: ./forms-gen-nest
            dockerfile: Dockerfile.forms-rest
        container_name: forms-gen-rest
        depends_on:
            rabbitmq:
                condition: service_started
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        environment:
            - PORT=8080
            - HOST=0.0.0.0
            - AMQP_URL=amqp://guest:guest@rabbitmq:5672
        ports:
            - 3000:8080


    forms-db:
        build: 
            context: ./forms-gen-nest
            dockerfile: Dockerfile.forms-db
        container_name: forms-gen-db
        depends_on:
            postgres:
                condition: service_started
            rabbitmq:
                condition: service_started
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        environment:
            - DATABASE_URL=postgres://root:root@postgres:5432/test
            - AMQP_URL=amqp://rabbitmq:5672
        command: bash -c "echo migrating && npm run prisma:forms-db:migrate --prefix=/app && echo launching && npm run start:forms-db:prod --prefix=/app" # should be removed if migration is not needed


    forms-discord:
        build: 
            context: ./forms-gen-nest
            dockerfile: Dockerfile.forms-discord
        container_name: forms-gen-discord
        depends_on:
            rabbitmq:
                condition: service_started
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        environment:
            - AMQP_URL=amqp://rabbitmq:5672
            - DISCORD_BOT_TOKEN=ABC


    angular:
        build: 
            context: ./forms-gen-angular
            dockerfile: Dockerfile
        container_name: forms-gen-angular
        restart: "on-failure"
        logging:
            options:
                max-size: "50m"
        ports:
            - 4200:80
