---
- name: Deploy Docker Project
  hosts: all
  become: true

  tasks:
      - name: Fail if "user_name" is undefined
        ansible.builtin.fail: msg="Bailing out. This play requires 'user_name'"
        when: user_name is undefined

      - name: Fail if "host_base" is undefined
        ansible.builtin.fail: msg="Bailing out. This play requires 'host_base'"
        when: host_base is undefined

      - name: Create swap
        ansible.builtin.include_role:
            name: geerlingguy.swap
        vars:
            swap_file_size_mb: "16384"
            swap_file_existing_size_mb: "16384"
            swap_file_state: present

      - name: Install aptitude
        apt:
            name: aptitude
            state: latest
            update_cache: true

      - name: Install required system packages
        apt:
            pkg:
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools
            state: latest
            update_cache: true

      - name: Add Docker GPG apt Key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add Docker Repository
        apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

      - name: Update apt and install docker-ce
        apt:
            name: docker-ce
            state: latest
            update_cache: true

      - name: Install docker-compose-plugin
        apt:
            name: docker-compose-plugin
            state: present

      - name: Install Docker Module for Python
        pip:
            name: docker

      - name: Download project from Git
        git:
            repo: https://github.com/6rayWa1cher/quizzer
            dest: /home/{{ user_name }}/quizzer/
            force: true

      - name: Configure forms-gen-angular/environment.prod.ts
        ansible.builtin.template:
            src: templates/environment.prod.ts.j2
            dest: /home/{{ user_name }}/quizzer/forms-gen-angular/src/environments/environment.prod.ts

      - name: Configure .env
        ansible.builtin.template:
            src: templates/.env.j2
            dest: /home/{{ user_name }}/quizzer/.env

      - name: Install UFW
        apt:
            name: ufw
            state: present

      - name: Allow HTTP
        community.general.ufw:
            rule: allow
            port: 80

      - name: Allow HTTPS
        community.general.ufw:
            rule: allow
            port: 443

      - name: Limit OpenSSH
        community.general.ufw:
            rule: limit
            name: OpenSSH

      - name: Enable UFW
        community.general.ufw:
            state: enabled

      - name: Deny everything
        community.general.ufw:
            policy: deny
