---
- name: Deploy Docker Project
  hosts: all
  become: true

  vars:
      swap_file_path: /swapfile
      swap_file_size: 16G
      project_path: /home/{{ user_name }}/quizzer

  tasks:
      - name: Fail if "user_name" is undefined
        fail: msg="Bailing out. This play requires 'user_name'"
        when: user_name is undefined

      - name: Fail if "host_base" is undefined
        fail: msg="Bailing out. This play requires 'host_base'"
        when: host_base is undefined

      - name: Check if swap exists
        stat:
            path: "{{ swap_file_path }}"
            get_checksum: false
        register: swap_file_check
        changed_when: false

      - name: Create swap
        shell: fallocate -l {{ swap_file_size }} {{ swap_file_path }}
        when: "not swap_file_check.stat.exists"

      - name: Fix permissions for swap
        file:
            path: "{{ swap_file_path }}"
            mode: 700
        when: "not swap_file_check.stat.exists"

      - name: Mark swap file
        shell: mkswap {{ swap_file_path }}
        when: "not swap_file_check.stat.exists"

      - name: Enable swap
        shell: swapon {{ swap_file_path }}
        when: "not swap_file_check.stat.exists"

      - name: Check swap
        shell: swapon --show
        register: swapon_check

      - name: Assert swap is connected
        assert:
            that: "'{{ swap_file_path }} in swapon_check.stdout'"

      - name: Install aptitude
        apt:
            name: aptitude
            state: latest
            update_cache: true

      - name: Update & upgrade all packages
        apt:
            name: "*"
            state: latest
            update_cache: true

      - name: Install required system packages
        apt:
            pkg:
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools
            state: latest
            update_cache: true

      - name: Add Docker GPG apt Key
        apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add Docker Repository
        apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

      - name: Update apt and install docker-ce
        apt:
            name: docker-ce
            state: latest
            update_cache: true

      - name: Install docker-compose-plugin
        apt:
            name: docker-compose-plugin
            state: present

      - name: Install Docker Module for Python
        pip:
            name: docker

      - name: Download project from Git
        git:
            repo: https://github.com/6rayWa1cher/quizzer
            dest: "{{ project_path }}"
            force: true

      - name: Configure forms-gen-angular/environment.prod.ts
        template:
            src: templates/environment.prod.ts.j2
            dest: "{{ project_path }}/forms-gen-angular/src/environments/environment.prod.ts"

      - name: Configure .env
        template:
            src: templates/.env.j2
            dest: "{{ project_path }}/.env"

      - name: Install UFW
        apt:
            name: ufw
            state: present

      - name: Allow HTTP
        community.general.ufw:
            rule: allow
            port: 80

      - name: Allow HTTPS
        community.general.ufw:
            rule: allow
            port: 443

      - name: Limit OpenSSH
        community.general.ufw:
            rule: limit
            name: OpenSSH

      - name: Enable UFW and deny everything
        community.general.ufw:
            policy: deny
            state: enabled

      - name: Tear down existing services
        shell: docker compose -f docker-compose.prod.yml down --remove-orphans
        args:
            chdir: "{{ project_path }}"

      - name: Deploy services
        shell: docker compose -f docker-compose.prod.yml up --build -d
        args:
            chdir: "{{ project_path }}"
        register: output

      - name: Show deploy results
        debug:
            var: output

      - name: Wait for service init
        pause:
            seconds: 45

      - name: Check running services
        shell: docker compose ps --services --status=running
        args:
            chdir: "{{ project_path }}"
        register: output

      - name: Show running services check results
        debug:
            var: output

      - name: Assert all necessary services are running
        assert:
            that:
                - "'traefik' in output.stdout"
                - "'postgres' in output.stdout"
                - "'rabbitmq' in output.stdout"
                - "'forms-rest' in output.stdout"
                - "'forms-db' in output.stdout"
                - "'angular' in output.stdout"
